<?php
require_once('data/best_of.php');
require_once('data/get_best_vainkeur.php');
require_once('data/get_contenders_ranking.php');
require_once('data/lastlogin.php');
require_once('data/get_data.php');
require_once('data/get_data_t.php');
require_once('data/get_user_data.php');
require_once('data/get_data_sponso.php');
require_once('data/get_users_by_level.php');
require_once('data/monitor_data.php');
require_once('data/get_resume.php');
require_once('data/played.php');
require_once('data/get_similar.php');
require_once('data/get_dodo.php');
