<?php
require_once 'meca/get_paid.php';
require_once 'meca/compil.php';
require_once 'meca/do_elo.php';
require_once 'meca/deal_vainkeur_entry.php';
require_once('meca/uniq_user_id.php');
require_once('meca/delete-ranking.php');
require_once 'meca/get_ranking.php';
require_once('meca/do_vote.php');
require_once 'meca/deal_counter.php';
require_once('meca/do_note.php');
require_once('meca/do_transaction.php');
require_once('meca/get_money.php');
require_once('meca/do_comment_note.php');
require_once('meca/mouv_timeline.php');
require_once 'meca/user_ranking.php';
require_once 'meca/check_battle.php';
require_once 'meca/deal-uuiduser.php';
require_once 'meca/deal-utm.php';
require_once 'meca/begin_t.php';
require_once 'meca/check_user_level.php';
require_once 'meca/newplayer.php';
require_once 'meca/vainkeur_badge.php';