<?php
include __DIR__ . '/../../../../wp-load.php';
/**
 * CRON JOB : Update money generated by activity for all creators users
 *
 * When : Everyday @ 02:15
 */
$user_query = new WP_User_Query(
    array(
        'number' => -1,
        'role__in' => array('administrator', 'author')
    )
);
$users = $user_query->get_results();
foreach ($users as $user) {
    $user_id = $user->ID;
    $vainkeur_entry = new WP_Query(array(
        'post_type'              => 'vainkeur',
        'posts_per_page'         => '1',
        'fields'                 => 'ids',
        'post_status'            => 'publish',
        'ignore_sticky_posts'    => true,
        'update_post_meta_cache' => false,
        'no_found_rows'          => false,
        'author'                 => $user_id
    ));

    if ($vainkeur_entry->have_posts()) {
        $id_vainkeur    = $vainkeur_entry->posts[0];
    }
    $total_money = get_creator_money_for_duplicated($user_id);
    update_field('money_duplication_vkrz', $total_money['money_duplicated'], $id_vainkeur);
}